all:
  children:
    managers:
      hosts:
        192.168.1.70:
        192.168.1.71:
        192.168.1.72:
    workers:
      hosts:
        192.168.1.110:
        192.168.1.111:
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
